/**
 * pages/Tasks.jsx
 * Task management — Phase 2 feature.
 * Displays a designed UI illustrating planned capability.
 * Tasks are generated by server-side logic from appointments, callbacks,
 * rescheduling events, and reminders.
 */

import { useState } from 'react';
import { s } from '../styles/tokens.js';

const MOCK_TASKS = [
  { id:1, title:'Call back Dr Priya Naidoo',            detail:'Callback requested · Due: Today 10:00',             dueLabel:'Overdue',   dueBg:'#fef2f2', dueColor:'#dc2626', done:false },
  { id:2, title:'Confirm appointment — Dr Sipho Dlamini',detail:'Appointment tomorrow 14:00 · Confirm with broker',  dueLabel:'Due today', dueBg:'#fffbeb', dueColor:'#d97706', done:false },
  { id:3, title:'Reschedule — Dr Amara Osei 2nd meeting',detail:'Client requested reschedule · Original: 20 May',   dueLabel:'Due today', dueBg:'#fffbeb', dueColor:'#d97706', done:false },
  { id:4, title:'Record outcome — Dr Lerato Mokoena',    detail:'First meeting completed — record outcome',           dueLabel:'Due 21 May',dueBg:'#eff6ff', dueColor:'#1d4ed8', done:false },
  { id:5, title:'Assign broker — Dr James van Rooyen',   detail:'Completed 14 May 2026',                             dueLabel:'Done',      dueBg:'#f0fdf4', dueColor:'#15803d', done:true  },
];

const TABS = [
  ['all',         'All tasks'],
  ['appointments','Appointments'],
  ['rescheduling','Rescheduling'],
  ['reminders',   'Reminders'],
];

export default function Tasks() {
  const [tab,   setTab]   = useState('all');
  const [tasks, setTasks] = useState(MOCK_TASKS);

  function toggleDone(id) {
    setTasks(prev => prev.map(t => t.id === id ? { ...t, done: !t.done } : t));
  }

  const pending   = tasks.filter(t => !t.done).length;
  const displayed = tasks.filter(t => tab === 'all' ? true : !t.done);

  return (
    <div style={{ ...s.page, maxWidth: '760px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px' }}>
        <div>
          <h1 style={{ margin: 0, fontSize: '1.375rem', fontWeight: 600, color: '#111827' }}>Tasks</h1>
          <p style={{ margin: '3px 0 0', fontSize: '0.813rem', color: '#6b7280' }}>
            Your pending actions across appointments, reminders, and scheduling
          </p>
        </div>
        <button style={{ ...s.primaryBtn, opacity: 0.6, cursor: 'not-allowed' }} disabled>+ New Task</button>
      </div>

      <div style={{ ...s.noticeWarn, marginBottom: '16px' }}>
        Task Management is a Phase 2 feature. The view below illustrates the planned capability — tasks
        will be generated automatically from appointment events, callback requests, and rescheduling actions.
      </div>

      {pending > 0 && (
        <div style={{ ...s.noticeInfo, marginBottom: '14px' }}>
          You have <strong>{pending} pending task{pending !== 1 ? 's' : ''}</strong>.
        </div>
      )}

      <div style={{ display: 'flex', borderBottom: '1px solid #e5e7eb', marginBottom: '16px' }}>
        {TABS.map(([key, label]) => (
          <button
            key={key}
            onClick={() => setTab(key)}
            style={{
              padding: '8px 16px', border: 'none', background: 'none', cursor: 'pointer',
              fontSize: '0.875rem', fontFamily: 'inherit',
              fontWeight: tab === key ? 600 : 400,
              color: tab === key ? '#1d4ed8' : '#6b7280',
              borderBottom: tab === key ? '2px solid #1d4ed8' : '2px solid transparent',
              marginBottom: '-1px',
            }}
          >
            {label}
          </button>
        ))}
      </div>

      <div style={s.card}>
        {displayed.length === 0 && (
          <div style={{ textAlign: 'center', padding: '32px', color: '#9ca3af', fontSize: '0.875rem' }}>
            No tasks in this category.
          </div>
        )}
        {displayed.map((task, i) => (
          <div
            key={task.id}
            style={{
              display: 'flex', alignItems: 'flex-start', gap: '12px',
              padding: '12px 0',
              borderBottom: i < displayed.length - 1 ? '1px solid #f3f4f6' : 'none',
            }}
          >
            {/* Checkbox */}
            <div
              onClick={() => toggleDone(task.id)}
              style={{
                width: '18px', height: '18px', borderRadius: '4px', flexShrink: 0,
                marginTop: '1px', cursor: 'pointer', display: 'flex', alignItems: 'center',
                justifyContent: 'center', fontSize: '0.75rem',
                border: task.done ? 'none' : '2px solid #d1d5db',
                background: task.done ? '#10b981' : 'white',
                color: 'white',
                transition: 'all 0.1s',
              }}
            >
              {task.done && '✓'}
            </div>

            {/* Content */}
            <div style={{ flex: 1 }}>
              <div style={{
                fontSize: '0.875rem', fontWeight: 500,
                color: task.done ? '#9ca3af' : '#111827',
                textDecoration: task.done ? 'line-through' : 'none',
                marginBottom: '2px',
              }}>
                {task.title}
              </div>
              <div style={{ fontSize: '0.8125rem', color: '#6b7280' }}>{task.detail}</div>
            </div>

            {/* Due badge */}
            <span style={{
              ...s.badge, fontSize: '0.688rem', flexShrink: 0,
              background: task.dueBg, color: task.dueColor,
            }}>
              {task.dueLabel}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
